config/routes.rb
Rails.application.routes.draw do
  
  
  scope "(:locale)", locale: /en|vn/ do
    root 'static_page#home'
    
    get 'admin' => 'admin#index'
    get 'resign' => 'static_page#new'
    post 'resign' => 'static_page#create'
    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy'
  
    resources :staffs, path: 'admin/staffs'
    resources :customers, path: 'admin/customers'
    resources :manufacturers, path: 'admin/manufacturers'
    resources :authors, path: 'admin/authors'
    resources :books, path: 'admin/books'
    resources :categories, path: 'admin/categories'
    resources :orders, path: 'admin/orders'
    resources :comments, path: 'admin/comments'
  end

end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
    before_save { self.email = email.downcase }
    validates :user, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
    @book = Book.all
  end
  
  def new
    @staff = Staff.new
  end
  
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to root_path }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def staff_params
      params.require(:staff).permit(:name, :birthday, :gender, :phone, :address, :email, :user, :password, :password_confirmation)
    end
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/static_page/home.html.erb
<div>
<!-- Main navbar -->
<div class="navbar navbar-inverse">
<ul class="nav navbar-nav navbar-right">
<li class="dropdown dropdown-user">
<%= link_to image_tag("placeholder.jpg", alt: "logo")+"<span>Victoria</span><i class='caret'></i>".html_safe, root_path, class: "dropdown-toggle", data: {toggle: "dropdown"} %>
<ul class="dropdown-menu dropdown-menu-right">
<li><%= link_to 'Resign', resign_path %></li>
<% if logged_in? %>
<li><%= link_to 'Log out', logout_path, method: "delete" %></li>
<% else %>
<li><%= link_to 'Log in', login_path %></li>
<% end %>
</ul>
</li>
</ul>
</div>
</div>
<!-- /main navbar -->
</div>
<div class="row">
	<div class="col-md-3" style="background: gray">
		aaaaaaaaaaaaaaaaaaaaaaaaa
	</div>
	<div class="col-md-9">
		<% @book.each do |book| %>
			<div class="col-md-4">
				<%= image_tag book.image_url.to_s, class: "list_image" %>
			</div>
			<div class="col-md-8">
				<p><%= book.name %></p>
				<p><%= book.price %></p>
			</div>
			<div class="clearfix"></div>
		<% end %>
	</div>
</div>

app/views/static_page/new.html.erb
<% provide(:title, "Them nhan vien")%>
<div class="content">
	<% flash.each do |message_type, message| %>
					<div class="alert alert-<%= message_type %>"><%= message %></div>
				<% end %>
				<div class="panel panel-flat">
					<div class="panel-heading">
						<h1 class="panel-title"><%= t('.newstaff') %></h1>
					</div>
                    <div class="panel-body">
                        <%= form_for(@staff, url: resign_path) do |f| %>
  <% if @staff.errors.any? %>
    <div class="error_explanation">
      <ul>
      <% @staff.errors.full_messages.each do |message| %>
        <div class="alert alert-warning alert-bordered">
          <button type="button" class="close" data-dismiss="alert"><span>×</span><span class="sr-only">Close</span></button>
          <span class="text-semibold">Warning! </span><%= message %>
        </div>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <legend class="text-semibold"><h5><%= t('.titleaccount')%></h5></legend>
	<div class="field required">
    <%= f.label :user, t('.user') %><br>
    <%= f.text_field :user, class:"form-control", placeholder:"Nhap ten tai khoan" %>
  </div>
	<div class="field required">
    <%= f.label :email, t('.email') %><br>
    <%= f.text_field :email, class:"form-control", placeholder:"eugene@kopyov.com" %>
		<span class="help-block">Accepted formats: example@gmail.com</span>
  </div>
	<div class="field required">
    <%= f.label :password, t('.password') %><br>
    <%= f.password_field :password, class:"form-control", placeholder:"Your strong password" %>
  </div>
  <div class="field required">
    <%= f.label :password_confirmation, t('.passwordconfirmation') %><br>
    <%= f.password_field :password_confirmation, class:"form-control", placeholder:"Repeat password"%>
  </div>
	
	<legend class="text-semibold"><h5><%= t('.titlepersonal')%></h5></legend>
  <div class="field">
    <%= f.label :name, t('.name') %><br>
    <%= f.text_field :name, class:"form-control", placeholder:"Nhap ten Nhan Vien" %>
  </div>
 <div class="field">
    <%= f.label :birthday, t('.birthday') %><br>
    <%= f.text_field :birthday, class:"form-control", id:"anytime-month-numeric", placeholder:"dd/mm/yyyy"%>
  </div>
  <div class="field">
    <%= f.label :gender, t('.gender'), class:"display-block" %><br>
		<%= f.label :gender_male,  t('.male'), class:"radio-inline" %>
    <%= f.radio_button :gender, 'Nam', class:"styled", :checked => true%>
    <%= f.label :gender_female,  t('.female'), class:"radio-inline" %>
    <%= f.radio_button :gender, 'Nữ', class:"styled" %><br />
  </div>
  <div class="field">
    <%= f.label :phone, t('.phone') %><br>
    <%= f.text_field :phone, :maxlength => 12, class:"form-control", placeholder:"+99-99-9999-9999", onkeypress: 'return event.charCode >= 48 && event.charCode <= 57' %>
  </div>
  <div class="field">
    <%= f.label :address, t('.address') %><br>
    <%= f.text_area :address, class:"form-control", placeholder:"Ring street 12" %>
  </div>
  <div class="actions text-right">
    <%= f.submit nil, :class => 'btn btn-primary'%>
		 <%= link_to t('.back'), root_path, class:"btn btn-primary" %>
  </div>
<% end %>
                    </div>
                </div>
            </div>
</div>
<%= javascript_include_tag 'uniform.min.js' %>
<%= javascript_include_tag 'form_layouts.js' %>
<%= javascript_include_tag 'select2.min.js' %>

<%= javascript_include_tag 'picker_date_authors.js' %>
<%= javascript_include_tag 'datepicker_authors.min.js' %>
<%= javascript_include_tag 'effects_authors.min.js' %>
<%= javascript_include_tag 'jgrowl_authors.min.js' %>
<%= javascript_include_tag 'moment_authors.min.js' %>
<%= javascript_include_tag 'daterangepicker_authors.js' %>
<%= javascript_include_tag 'anytime_authors.min.js' %>
<%= javascript_include_tag 'picker_authors.js' %>
<%= javascript_include_tag 'picker.date_authors.js' %>
<%= javascript_include_tag 'picker.time_authors.js' %>
<%= javascript_include_tag 'legacy_authors.js' %>