config/routes.rb
Rails.application.routes.draw do
  
  
  scope "(:locale)", locale: /en|vn/ do
    root 'static_page#home'
    
    get 'admin' => 'admin#index'
    get 'resign' => 'static_page#new'
    post 'resign' => 'static_page#create'
    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy'
  
    resources :staffs, path: 'admin/staffs'
    resources :customers, path: 'admin/customers'
    resources :manufacturers, path: 'admin/manufacturers'
    resources :authors, path: 'admin/authors'
    resources :books, path: 'admin/books'
    resources :categories, path: 'admin/categories'
    resources :orders, path: 'admin/orders'
    resources :comments, path: 'admin/comments'
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    validates :name, :comment, presence: true
    validates :user, presence: true, length: { maximum: 50 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authentication
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        flash[:success] = 'Comment was successfully created.'
        format.html { redirect_to @comment }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        flash[:success] = 'Comment was successfully updated.'
        format.html { redirect_to @comment}
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      flash[:success] = 'Comment was successfully destroyed.'
      format.html { redirect_to comments_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:name, :comment, :user)
    end
    
    def authentication
      if logged_in?
      else
        redirect_to login_path
      end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div class="error_explanation">
      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <div class="alert alert-warning alert-bordered">
          <button type="button" class="close" data-dismiss="alert"><span>×</span><span class="sr-only">Close</span></button>
          <span class="text-semibold">Warning! </span><%= message %>
        </div>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, t('.name') %><br>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :comment, t('.ndcomment') %><br>
    <%= f.text_area :comment, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :user, t('.user') %><br>
    <%= f.text_field :user, class:"form-control" %>
  </div>
  <div class="actions text-right">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to  t('.back'), comments_path, class:"btn btn-primary"  %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<% provide(:title,t('.editcomment'))%>
<%= render 'admin/shared/nav'%>
<div class="page-container">
    <div class="page-content">
        <div class="sidebar sidebar-main">
            <%= render 'admin/shared/sidebar'%>
        </div>
        <div class="content-wrapper">
            <div class="page-header">
                <div class="page-header-content">
                    <div class="page-title">
                        <h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold"><%= t('.editcomment')%></span></h4>
                    </div>
                </div>
                <div class="breadcrumb-line">
						<ul class="breadcrumb">
								<li>
									<%= link_to "<i class='icon-home2 position-left'></i>".html_safe + t('.dashboard'), admin_path %>
								</li>
								<li><%= link_to  t('.comment'), comments_path %></li>
								<li><%= link_to t('.listcomment') , comments_path %></li>
								<li><%= t('.editcomment')%></li>
						</ul>
					</div>
            </div>
<div class="content">
	<% flash.each do |message_type, message| %>
					<div class="alert alert-<%= message_type %>"><%= message %></div>
				<% end %>
    <div class="panel panel-flat">
					<div class="panel-heading">
						<h1 class="panel-title"><%= t('.editcomment')%></h1>
					</div>
                    <div class="panel-body">
                        <%= render 'form' %>
                    </div>
                </div>
            </div>
</div>
    </div>
</div>
<%= javascript_include_tag 'uniform.min.js' %>
<%= javascript_include_tag 'form_layouts.js' %>
<%= javascript_include_tag 'select2.min.js' %>

<%= javascript_include_tag 'picker_date_authors.js' %>
<%= javascript_include_tag 'datepicker_authors.min.js' %>
<%= javascript_include_tag 'effects_authors.min.js' %>
<%= javascript_include_tag 'jgrowl_authors.min.js' %>
<%= javascript_include_tag 'moment_authors.min.js' %>
<%= javascript_include_tag 'daterangepicker_authors.js' %>
<%= javascript_include_tag 'anytime_authors.min.js' %>
<%= javascript_include_tag 'picker_authors.js' %>
<%= javascript_include_tag 'picker.date_authors.js' %>
<%= javascript_include_tag 'picker.time_authors.js' %>
<%= javascript_include_tag 'legacy_authors.js' %>

<%= javascript_include_tag 'bootstrap_select.min.js' %>
<%= javascript_include_tag 'form_bootstrap_select.js' %>

app/views/comments/index.html.erb
<% provide(:title, t('.listcomment'))%>
<%= render 'admin/shared/nav'%>
<div class="page-container">
    <div class="page-content">
        <div class="sidebar sidebar-main">
            <%= render 'admin/shared/sidebar'%>
        </div>
        <div class="content-wrapper">
            <div class="page-header">
                <div class="page-header-content">
                    <div class="page-title">
                        <h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold"><%= t('.listcomment')%></span></h4>
                    </div>
                </div>
                <div class="breadcrumb-line">
						<ul class="breadcrumb">
							<li>
								<%= link_to "<i class='icon-home2 position-left'></i>".html_safe + t('.dashboard'), admin_path %>
							</li>
							<li><%= link_to  t('.comment'), comments_path %></li>
							<li><%= t('.listcomment')%></li>
						</ul>
					</div>
            </div>
<div class="content">
  <!-- Basic datatable -->
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h1 class="panel-title"><%= t('.listcomment')%></h1>
				<div class="heading-elements">
					<ul class="icons-list">
						<li class="custombutton"><%= link_to t('.addnew'), new_comment_path, class:"btn btn-primary" %></li>
					</ul>
				</div>
        </div>
  <table class="table datatable-basic table-hover">
  <thead>
    <tr>
      <th><%= t('.name')%></th>
      <th><%= t('.ndcomment')%></th>
      <th><%= t('.user')%></th>
      <th class="text-center"><%= t('.action')%></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%=link_to comment.name, edit_comment_path(comment) %></td>
        <td><%= comment.comment %></td>
        <td><%= comment.user %></td>
        <td class="text-center">
          <ul class="icons-list">
            <li class="dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                 <i class="icon-menu9"></i>
                  </a>

                  <ul class="dropdown-menu dropdown-menu-right">
                     <li><%= link_to t('.show'), comment %></li>
                     <li><%= link_to t('.edit'), edit_comment_path(comment) %></li>
                    <li><%= link_to t('.destroy'), comment, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                 </ul>
              </li>
           </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
    <!-- /basic datatable -->
</div>
</div>
</div>
</div>
<%= javascript_include_tag 'datatables.min.js' %>
<%= javascript_include_tag 'datatables_basic_comment.js' %>
<%= javascript_include_tag 'select2.min.js' %>
<%= javascript_include_tag 'bootbox.min.js' %>
<%= javascript_include_tag 'sweet_alert.min.js' %>
<%= javascript_include_tag 'components_modals.js' %>

app/views/comments/new.html.erb
<% provide(:title, t('.newcomment'))%>
<%= render 'admin/shared/nav'%>
<div class="page-container">
    <div class="page-content">
        <div class="sidebar sidebar-main">
            <%= render 'admin/shared/sidebar'%>
        </div>
        <div class="content-wrapper">
            <div class="page-header">
                <div class="page-header-content">
                    <div class="page-title">
                        <h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold"><%= t('.newcomment')%></span></h4>
                    </div>
                </div>
                <div class="breadcrumb-line">
						<ul class="breadcrumb">
							<ul class="breadcrumb">
								<li>
									<%= link_to "<i class='icon-home2 position-left'></i>".html_safe + t('.dashboard'), admin_path %>
								</li>
								<li><%= link_to  t('.comment'), comments_path %></li>
								<li><%= link_to t('.listcomment') , comments_path %></li>
								<li><%= t('.newcomment')%></li>
						</ul>
					</div>
            </div>
<div class="content">
	<% flash.each do |message_type, message| %>
					<div class="alert alert-<%= message_type %>"><%= message %></div>
				<% end %>
    <div class="panel panel-flat">
					<div class="panel-heading">
						<h1 class="panel-title"><%= t('.newcomment')%></h1>
					</div>
                    <div class="panel-body">
                        <%= render 'form' %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<%= javascript_include_tag 'uniform.min.js' %>
<%= javascript_include_tag 'form_layouts.js' %>
<%= javascript_include_tag 'select2.min.js' %>

<%= javascript_include_tag 'picker_date_authors.js' %>
<%= javascript_include_tag 'datepicker_authors.min.js' %>
<%= javascript_include_tag 'effects_authors.min.js' %>
<%= javascript_include_tag 'jgrowl_authors.min.js' %>
<%= javascript_include_tag 'moment_authors.min.js' %>
<%= javascript_include_tag 'daterangepicker_authors.js' %>
<%= javascript_include_tag 'anytime_authors.min.js' %>
<%= javascript_include_tag 'picker_authors.js' %>
<%= javascript_include_tag 'picker.date_authors.js' %>
<%= javascript_include_tag 'picker.time_authors.js' %>
<%= javascript_include_tag 'legacy_authors.js' %>

<%= javascript_include_tag 'bootstrap_select.min.js' %>
<%= javascript_include_tag 'form_bootstrap_select.js' %>

app/views/comments/show.html.erb
<% provide(:title,t('.showcomment'))%>
<%= render 'admin/shared/nav'%>
<div class="page-container">
    <div class="page-content">
        <div class="sidebar sidebar-main">
            <%= render 'admin/shared/sidebar'%>
        </div>
        <div class="content-wrapper">
            <div class="page-header">
                <div class="page-header-content">
                    <div class="page-title">
                        <h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold"><%= t('.showcomment')%></span></h4>
                    </div>
                </div>
                <div class="breadcrumb-line">
						<ul class="breadcrumb">
								<li>
									<%= link_to "<i class='icon-home2 position-left'></i>".html_safe + t('.dashboard'), admin_path %>
								</li>
								<li><%= link_to  t('.comment'), comments_path %></li>
								<li><%= link_to t('.listcomment') , comments_path %></li>
								<li><%= t('.showcomment')%></li>
						</ul>
					</div>
            </div>
             <div class="content">
              <div class="panel panel-flat">
                  <div class="panel-heading">
                    <h1 class="panel-title"><%= t('.showcomment')%></h1>
                  </div>
                    <div class="panel-body">
                      <p>
                        <strong><%= t('.name')%></strong>
                        <%= @comment.name %>
                      </p>
                      
                      <p>
                        <strong><%= t('.ndcomment')%></strong>
                        <%= @comment.comment %>
                      </p>
                      
                      <p>
                        <strong><%= t('.user')%></strong>
                        <%= @comment.user %>
                      </p>
                       <div class="clearfix"></div>    
                        <div class="text-right">
                            <%= link_to t('.edit'), edit_comment_path(@comment), class:"btn btn-primary" %>
                            <%= link_to t('.back'), comments_path, class:"btn btn-primary" %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<%= javascript_include_tag 'uniform.min.js' %>
<%= javascript_include_tag 'form_layouts.js' %>
<%= javascript_include_tag 'select2.min.js' %>

<%= javascript_include_tag 'components_thumbnails.js' %>
<%= javascript_include_tag 'fancybox.min.js' %>
<%= javascript_include_tag 'switchery.min.js' %>