config/routes.rb
Rails.application.routes.draw do
  
  
  scope "(:locale)", locale: /en|vn/ do
    root 'static_page#home'
    
    get 'admin' => 'admin#index'
    get 'resign' => 'static_page#new'
    post 'resign' => 'static_page#create'
    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy'
  
    resources :staffs, path: 'admin/staffs'
    resources :customers, path: 'admin/customers'
    resources :manufacturers, path: 'admin/manufacturers'
    resources :authors, path: 'admin/authors'
    resources :books, path: 'admin/books'
    resources :categories, path: 'admin/categories'
    resources :orders, path: 'admin/orders'
    resources :comments, path: 'admin/comments'
  end

end

app/models/author.rb
class Author < ActiveRecord::Base
    has_many :book, dependent: :nullify
    
    validates :name, uniqueness: { case_sensitive: false }
    validates :name, :birthday, :description, :homeland, presence:true
end

app/models/book.rb
class Book < ActiveRecord::Base
    belongs_to :staff
    belongs_to :author
    belongs_to :manufacturer
    has_and_belongs_to_many :category
    
    validates :name, uniqueness: { case_sensitive: false }
    validates :name, :description, :price, :image_url, :image, presence: true
    validates :image_url, allow_blank: true, format: {
        with: %r{\.(gif|jpg|png)\Z}i,
        message: 'must be a URL for GIF, JPG or PNG image.'
        }
    attr_accessor :image
    mount_uploader :image, ImageUploader
    #them attr_accessor :image,  mount_uploader :image, ImageUploader
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_and_belongs_to_many :book
    
    validates :name, uniqueness: { case_sensitive: false }
    validates :name, :description , presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    validates :name, :comment, presence: true
    validates :user, presence: true, length: { maximum: 50 }
end

app/models/customer.rb
class Customer < ActiveRecord::Base
    validates :phone, numericality: true
    validates :name, :birthday, :gender, :address, presence: true
    before_save { self.email = email.downcase }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
    has_many :book, dependent: :nullify
    
    validates :name, uniqueness: { case_sensitive: false }
    validates :phone, :fax, numericality: true
    validates :name, :address, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
     before_save { self.email = email.downcase }
     validates :name, :method, presence: true, length: { maximum: 50 }
     VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/ix
     validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
end

app/models/staff.rb
class Staff < ActiveRecord::Base
    has_many :book, dependent: :nullify
    
    before_save { self.email = email.downcase }
    validates :user, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    has_secure_password
    /validates :password, presence: true, length: { minimum: 6 }*/
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
    before_save { self.email = email.downcase }
    validates :user, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title = '')
        base_title = "Bookstore";
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(staff)
        session[:staff_id] = staff.id
    end
    
    def current_staff
        @current_staff ||= Staff.find_by(id: session[:staff_id])
    end
    
    def logged_in?
        !current_staff.nil?
    end
    
    def log_out_admin
        session.delete(:staff_id)
        @current_staff = nil
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/admin/index.html.erb
<% provide(:title, "Admin")%>
<%= render 'admin/shared/nav'%>
<div class="page-container">
    <div class="page-content">
        <div class="sidebar sidebar-main">
            <%= render 'admin/shared/sidebar'%>
        </div>
        <div class="content-wrapper">
			<div class="page-header">
                <div class="page-header-content">
                    <div class="page-title">
                        <h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold"><%= t('.dashboard')%></span></h4>
                    </div>
                </div>
                <div class="breadcrumb-line">
						<ul class="breadcrumb">
							<li>
                                <%= link_to "<i class='icon-home2 position-left'></i><span>Home</span>".html_safe, admin_path %>
                            </li>
							<li><%= t('.dashboard')%></li>
						</ul>
					</div>
            </div>
            <% flash.each do |message_type, message| %>
				<div class="alert alert-<%= message_type %>"><%= message %></div>
			<% end %>
            <h1 style="text-align: center"><%= t('.hello') + current_staff.name %></h1>
        </div>
    </div>
</div>

app/views/admin/shared/_nav.html.erb

	<!-- Main navbar -->
	<div class="navbar navbar-inverse">
		<div class="navbar-header">
			<%= link_to image_tag("logo_light.png", alt: "logo"), admin_path , class:"navbar-brand"%>
			<ul class="nav navbar-nav pull-right visible-xs-block">
				<li><a data-toggle="collapse" data-target="#navbar-mobile"><i class="icon-tree5"></i></a></li>
				<li><a class="sidebar-mobile-main-toggle"><i class="icon-paragraph-justify3"></i></a></li>
			</ul>
		</div>

		<div class="navbar-collapse collapse" id="navbar-mobile">
			<ul class="nav navbar-nav">
				<li>
					<a class="sidebar-control sidebar-main-toggle hidden-xs">
						<i class="icon-paragraph-justify3"></i>
					</a>
				</li>
			</ul>

			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown language-switch">
					<% if I18n.locale == I18n.default_locale %>
						<%= link_to image_tag("gb.png", alt: "logo", class: "position-left") +' English<span class="caret"></span>'.html_safe, admin_path, class:"dropdown-toggle", data: {toggle: "dropdown"}%>
					<% else %>
						<%= link_to image_tag("vn.png", alt: "logo", class: "position-left") +' VietNam<span class="caret"></span>'.html_safe, admin_path, class:"dropdown-toggle", data: {toggle: "dropdown"}%>
					<% end %>
					<ul class="dropdown-menu">
						<li><%= link_to image_tag("gb.png", alt: "logo") + 'English'.html_safe, locale: :en %></li>
						<li><%= link_to image_tag("vn.png", alt: "logo") + 'VietNam'.html_safe, locale: :vn %></li>
					</ul>
				</li>
				
				<li class="dropdown dropdown-user">
						<%= link_to image_tag("logo_admin.png", alt: "logo")+"<span>".html_safe+current_staff.name+"</span><i class='caret'></i>".html_safe, admin_path, class: "dropdown-toggle", data: {toggle: "dropdown"} %>
					<ul class="dropdown-menu dropdown-menu-right">
						<li><%= link_to '<i class="icon-user-plus"></i>'.html_safe + t('.profile'), staff_path(current_staff.id) %></li>
						<li class="divider"></li>
						<li><%= link_to '<i class="icon-exit3"></i>'.html_safe + t('.out'), logout_path, method: "delete" %></li>
					</ul>
				</li>
			</ul>
		</div>
	</div>
	<!-- /main navbar -->

app/views/admin/shared/_sidebar.html.erb
<div class="sidebar-content">
    <!-- User menu -->
    <div class="sidebar-user">
        <div class="category-content">
            <div class="media">
                <%= link_to image_tag("logo_admin.png", alt: "logo", class: "img-circle img-sm"), admin_path , class:"media-left" %>
                <div class="media-body">
                    <span class="media-heading text-semibold"><%= current_staff.name %></span>
                    <div class="text-size-mini text-muted">
                        <i class="icon-pin text-size-small"></i><%= current_staff.address %>
                    </div>
                </div>

                <div class="media-right media-middle">
                    <ul class="icons-list">
                        <li>
                            <%= link_to '<i class="icon-cog3"></i>'.html_safe, edit_staff_path(current_staff.id)%>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- /user menu -->


    <!-- Main navigation -->
    <div class="sidebar-category sidebar-category-visible">
        <div class="category-content no-padding">
            <ul class="navigation navigation-main navigation-accordion">
                <!-- Main -->
                <li class="navigation-header"><span><%= t('.title') %></span> <i class="icon-menu" title="Main pages"></i>
                </li>
                <li><%= link_to "<i class='icon-home4'></i>".html_safe+t('.dashboard'), admin_path %>
                </li>
                <li>
                    <%= link_to "<i class='icon-stack2'></i>".html_safe+t('.list'), admin_path %>
                    <ul>
                        <li><%= active_link_to t('.listcategories'), categories_path, :wrap_tag => :li %></li>
                        <li><%= active_link_to t('.listbooks'), books_path, :wrap_tag => :li %></li>
                        <li><%= active_link_to t('.listauthors'), authors_path, :wrap_tag => :li %></li>
                        <li><%= active_link_to t('.listmanufacturers'), manufacturers_path, :wrap_tag => :li %></li>
                    </ul>
                </li>
                <li>
                    <%= link_to "<i class='icon-file-text'></i>".html_safe+t('.order'), orders_path %>
                </li>
                <li>
                    <%= link_to "<i class='icon-pen6'></i>".html_safe+t('.comment'), comments_path %>
                </li>
                <li>
                    <%= link_to "<i class='icon-profile'></i>".html_safe+t('.information'), admin_path %>
                    <ul>
                        <li><%= active_link_to t('.informationcustomers'), customers_path, :wrap_tag => :li %></li>
                        <li><%= active_link_to t('.informationstaffs'), staffs_path, :wrap_tag => :li %></li>
                    </ul>
                </li>
                
                <!-- /main -->
            </ul>
        </div>
    </div>
    <!-- /main navigation -->

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "/stylesheets/style.css" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>