config/routes.rb
Rails.application.routes.draw do
  
  
  scope "(:locale)", locale: /en|vn/ do
    root 'static_page#home'
    
    get 'admin' => 'admin#index'
    get 'resign' => 'static_page#new'
    post 'resign' => 'static_page#create'
    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy'
  
    resources :staffs, path: 'admin/staffs'
    resources :customers, path: 'admin/customers'
    resources :manufacturers, path: 'admin/manufacturers'
    resources :authors, path: 'admin/authors'
    resources :books, path: 'admin/books'
    resources :categories, path: 'admin/categories'
    resources :orders, path: 'admin/orders'
    resources :comments, path: 'admin/comments'
  end

end

app/models/author.rb
class Author < ActiveRecord::Base
    has_many :book, dependent: :nullify
    
    validates :name, uniqueness: { case_sensitive: false }
    validates :name, :birthday, :description, :homeland, presence:true
end

app/models/book.rb
class Book < ActiveRecord::Base
    belongs_to :staff
    belongs_to :author
    belongs_to :manufacturer
    has_and_belongs_to_many :category
    
    validates :name, uniqueness: { case_sensitive: false }
    validates :name, :description, :price, :image_url, :image, presence: true
    validates :image_url, allow_blank: true, format: {
        with: %r{\.(gif|jpg|png)\Z}i,
        message: 'must be a URL for GIF, JPG or PNG image.'
        }
    attr_accessor :image
    mount_uploader :image, ImageUploader
    #them attr_accessor :image,  mount_uploader :image, ImageUploader
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_and_belongs_to_many :book
    
    validates :name, uniqueness: { case_sensitive: false }
    validates :name, :description , presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    validates :name, :comment, presence: true
    validates :user, presence: true, length: { maximum: 50 }
end

app/models/customer.rb
class Customer < ActiveRecord::Base
    validates :phone, numericality: true
    validates :name, :birthday, :gender, :address, presence: true
    before_save { self.email = email.downcase }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
    has_many :book, dependent: :nullify
    
    validates :name, uniqueness: { case_sensitive: false }
    validates :phone, :fax, numericality: true
    validates :name, :address, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
     before_save { self.email = email.downcase }
     validates :name, :method, presence: true, length: { maximum: 50 }
     VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/ix
     validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
end

app/models/staff.rb
class Staff < ActiveRecord::Base
    has_many :book, dependent: :nullify
    
    before_save { self.email = email.downcase }
    validates :user, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    has_secure_password
    /validates :password, presence: true, length: { minimum: 6 }*/
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
    before_save { self.email = email.downcase }
    validates :user, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authentication
  
  def index
    if params[:set_locale]
      redirect_to admin_url(locale: params[:set_locale])
    end
  end
  
  def authentication
    if logged_in?
    else
      redirect_to login_path
    end
  end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  before_action :authentication
  before_action :set_manufacturer, only: [:show, :edit, :update, :destroy]

  # GET /manufacturers
  # GET /manufacturers.json
  def index
    @manufacturers = Manufacturer.all
  end

  # GET /manufacturers/1
  # GET /manufacturers/1.json
  def show
    if current_staff.admin
    else
      redirect_to manufacturers_path
    end
  end

  # GET /manufacturers/new
  def new
    if current_staff.admin
      @manufacturer = Manufacturer.new
    else
      redirect_to manufacturers_path
    end
  end

  # GET /manufacturers/1/edit
  def edit
    if current_staff.admin
    else
      redirect_to manufacturers_path
    end
  end

  # POST /manufacturers
  # POST /manufacturers.json
  def create
    @manufacturer = Manufacturer.new(manufacturer_params)

    respond_to do |format|
      if @manufacturer.save
        flash[:success] = 'Manufacturer was successfully created.'
        format.html { redirect_to new_manufacturer_path }
        format.json { render :show, status: :created, location: @manufacturer }
      else
        format.html { render :new }
        format.json { render json: @manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manufacturers/1
  # PATCH/PUT /manufacturers/1.json
  def update
    respond_to do |format|
      if @manufacturer.update(manufacturer_params)
        flash[:success] = 'Manufacturer was successfully updated.'
        format.html { redirect_to edit_manufacturer_path }
        format.json { render :show, status: :ok, location: @manufacturer }
      else
        format.html { render :edit }
        format.json { render json: @manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manufacturers/1
  # DELETE /manufacturers/1.json
  def destroy
    @manufacturer.destroy
    respond_to do |format|
      flash[:success] = 'Manufacturer was successfully destroyed.'
      format.html { redirect_to manufacturers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manufacturer
      @manufacturer = Manufacturer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manufacturer_params
      params.require(:manufacturer).permit(:name, :address, :phone, :fax)
    end
    
    def authentication
    if logged_in?
    else
      redirect_to login_path
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title = '')
        base_title = "Bookstore";
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(staff)
        session[:staff_id] = staff.id
    end
    
    def current_staff
        @current_staff ||= Staff.find_by(id: session[:staff_id])
    end
    
    def logged_in?
        !current_staff.nil?
    end
    
    def log_out_admin
        session.delete(:staff_id)
        @current_staff = nil
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/layouts/manufacturers/_form.html.erb
<%= form_for(@manufacturer) do |f| %>
  <% if @manufacturer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manufacturer.errors.count, "error") %> prohibited this manufacturer from being saved:</h2>

      <ul>
      <% @manufacturer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:"form-control", placeholder:"Nhap ten Nha San Xuat" %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address, class:"form-control", placeholder:"Nhap Dia Chi Nha San Xuat" %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class:"form-control", placeholder:"Nhap So dien Thoai Nha San Xuat" %>
  </div>
  <div class="field">
    <%= f.label :fax %><br>
    <%= f.text_field :fax, class:"form-control", placeholder:"Nhap So fax Nha San Xuat" %>
  </div>
  <div class="actions text-right">
    <%= f.submit nil, :class => 'btn btn-primary'%>
    <%= link_to 'Back', manufacturers_path, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/layouts/manufacturers/edit.html.erb
<% provide(:title, "Chinh sua nha san xuat")%>
<% content_for :admin do %>
<%= render 'admin/shared/nav'%>
<div class="page-container">
    <div class="page-content">
        <div class="sidebar sidebar-main">
            <%= render 'admin/shared/sidebar'%>
        </div>
        <div class="content-wrapper">
			<div class="page-header">
                <div class="page-header-content">
                    <div class="page-title">
                        <h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">Editing Manufacturer</span></h4>
                    </div>
                </div>
                <div class="breadcrumb-line">
						<ul class="breadcrumb">
							<li>
                                <%= link_to "<i class='icon-home2 position-left'></i> <span>Dashboard</span>".html_safe, root_path %>
                            </li>
							<li><%= link_to "<span>Dang sach</span>".html_safe, manufacturers_path %></li>
							<li><%= link_to "Listing Manufacturers" , manufacturers_path %></li>
							<li class="active"><%= link_to "Editing Manufacturer" , edit_manufacturer_path %></li>
						</ul>
					</div>
            </div>
<div class="content">
				<div class="panel panel-flat">
					<div class="panel-heading">
						<h1 class="panel-title">Editing Manufacturer</h1>
                            <div class="heading-elements">
								<ul class="icons-list">
						            <li><a data-action="collapse"></a></li>
						            <li><a data-action="reload"></a></li>
						        </ul>
					        </div>
					</div>
                    <div class="panel-body">
                        <%= render 'form' %>
                    </div>
                </div>
            </div>
</div>
    </div>
</div>
<%= javascript_include_tag 'uniform.min.js' %>
<%= javascript_include_tag 'form_layouts.js' %>
<%= javascript_include_tag 'select2.min.js' %>
<% end %>

app/views/layouts/manufacturers/index.html.erb
<% provide(:title, "Danh sach nha san xuat")%>
<% content_for :admin do %>
<%= render 'admin/shared/nav'%>
<div class="page-container">
    <div class="page-content">
        <div class="sidebar sidebar-main">
            <%= render 'admin/shared/sidebar'%>
        </div>
        <div class="content-wrapper">
            <div class="page-header">
                <div class="page-header-content">
                    <div class="page-title">
                        <h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">Listing Manufacturers</span></h4>
                    </div>
                </div>
                <div class="breadcrumb-line">
						<ul class="breadcrumb">
							<li>
                                <%= link_to "<i class='icon-home2 position-left'></i> <span>Dashboard</span>".html_safe, root_path %>
                            </li>
							<li><%= link_to "<span>Dang sach</span>".html_safe, manufacturers_path %></li>
							<li class="active"><%= link_to "Listing Manufacturers" , manufacturers_path %></li>
						</ul>
					</div>
            </div>
<div class="content">
<!-- Basic datatable -->
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h1 class="panel-title">Listing Manufacturers</h1>
            <div class="heading-elements">
                <ul class="icons-list">
                    <li class="custombutton"><%= link_to 'New Manufacturer', new_manufacturer_path, class:"btn btn-primary" %></li>
                    <li><a data-action="collapse"></a></li>
                    <li><a data-action="reload"></a></li>
                </ul>
            </div>
        </div>

        

        <table class="table datatable-basic">
            <thead>
                <tr>
                     <th>Name</th>
                    <th>Address</th>
                    <th>Phone</th>
                    <th>Fax</th>
                    <th class="text-center">Action</th>
                </tr>
            </thead>
            <tbody>
                  <% @manufacturers.each do |manufacturer| %>
                    <tr>
                       <td><%= manufacturer.name %></td>
                        <td><%= manufacturer.address %></td>
                        <td><%= manufacturer.phone %></td>
                        <td><%= manufacturer.fax %></td>
                      <td class="text-center">
                            <ul class="icons-list">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <i class="icon-menu9"></i>
                                    </a>

                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <li><%= link_to 'Show', manufacturer %></li>
                                        <li><%= link_to 'Edit', edit_manufacturer_path(manufacturer) %></li>
                                        <li><%= link_to 'Destroy', manufacturer, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                                    </ul>
                                </li>
                            </ul>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
    <!-- /basic datatable -->
</div>
        </div>
    </div>
</div>
<%= javascript_include_tag 'datatables.min.js' %>
<%= javascript_include_tag 'datatables_basic_manufacturers.js' %>
<%= javascript_include_tag 'select2.min.js' %>
<%= javascript_include_tag 'bootbox.min.js' %>
<%= javascript_include_tag 'sweet_alert.min.js' %>
<%= javascript_include_tag 'components_modals.js' %>
<% end %>

app/views/layouts/manufacturers/new.html.erb
<% provide(:title, "Them nha san xuat")%>
<% content_for :admin do %>
<%= render 'admin/shared/nav'%>
<div class="page-container">
    <div class="page-content">
        <div class="sidebar sidebar-main">
            <%= render 'admin/shared/sidebar'%>
        </div>
        <div class="content-wrapper">
			<div class="page-header">
                <div class="page-header-content">
                    <div class="page-title">
                        <h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">New Manufacturer</span></h4>
                    </div>
                </div>
                <div class="breadcrumb-line">
						<ul class="breadcrumb">
							<li>
                                <%= link_to "<i class='icon-home2 position-left'></i> <span>Dashboard</span>".html_safe, root_path %>
                            </li>
							<li><%= link_to "<span>Dang sach</span>".html_safe, manufacturers_path %></li>
							<li><%= link_to "Listing Manufacturers" , manufacturers_path %></li>
							<li class="active"><%= link_to "New Manufacturer" , new_manufacturer_path %></li>
						</ul>
					</div>
            </div>
<div class="content">
				<div class="panel panel-flat">
					<div class="panel-heading">
						<h1 class="panel-title">New Manufacturer</h1>
                            <div class="heading-elements">
								<ul class="icons-list">
						            <li><a data-action="collapse"></a></li>
						            <li><a data-action="reload"></a></li>
						        </ul>
					        </div>
					</div>
                    <div class="panel-body">
                        <%= render 'form' %>
                    </div>
                </div>
            </div>
</div>
    </div>
</div>
<%= javascript_include_tag 'uniform.min.js' %>
<%= javascript_include_tag 'form_layouts.js' %>
<%= javascript_include_tag 'select2.min.js' %>
<% end %>

app/views/layouts/manufacturers/show.html.erb
<% provide(:title, "Chi tiet nha san xuat")%>
<% content_for :admin do %>
<%= render 'admin/shared/nav'%>
<div class="page-container">
    <div class="page-content">
        <div class="sidebar sidebar-main">
            <%= render 'admin/shared/sidebar'%>
        </div>
        <div class="content-wrapper">
			<div class="page-header">
                <div class="page-header-content">
                    <div class="page-title">
                        <h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">Show Manufacturers</span></h4>
                    </div>
                </div>
                <div class="breadcrumb-line">
						<ul class="breadcrumb">
							<li>
                                <%= link_to "<i class='icon-home2 position-left'></i> <span>Dashboard</span>".html_safe, root_path %>
                            </li>
							<li><%= link_to "<span>Dang sach</span>".html_safe, manufacturers_path %></li>
							<li><%= link_to "Listing Manufacturers" , manufacturers_path %></li>
							<li class="active"><%= link_to "Show Manufacturers" , manufacturer_path %></li>
						</ul>
					</div>
            </div>
<div class="content">
				<div class="panel panel-flat">
					<div class="panel-heading">
						<h1 class="panel-title">Show Manufacturers</h1>
                            <div class="heading-elements">
								<ul class="icons-list">
						            <li><a data-action="collapse"></a></li>
						            <li><a data-action="reload"></a></li>
						        </ul>
					        </div>
					</div>
                    <div class="panel-body">
                                            
                    <p>
                      <strong>Name:</strong>
                      <%= @manufacturer.name %>
                    </p>
                    
                    <p>
                      <strong>Address:</strong>
                      <%= @manufacturer.address %>
                    </p>
                    
                    <p>
                      <strong>Phone:</strong>
                      <%= @manufacturer.phone %>
                    </p>
                    
                    <p>
                      <strong>Fax:</strong>
                      <%= @manufacturer.fax %>
                    </p>

                        <div class="text-right">
                            <%= link_to 'Edit', edit_manufacturer_path(@manufacturer), class:"btn btn-primary" %>
                            <%= link_to 'Back', manufacturers_path, class:"btn btn-primary" %>
                        </div>
                    </div>
                </div>
            </div>
</div>
    </div>
</div>
<%= javascript_include_tag 'uniform.min.js' %>
<%= javascript_include_tag 'form_layouts.js' %>
<%= javascript_include_tag 'select2.min.js' %>
<% end %>